# Generated by Django 3.2.9 on 2021-11-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPa', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña (escoge una contraseña segura):')),
            ],
        ),
    ]
